# Generated by Django 4.2.1 on 2023-05-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Title', models.CharField(max_length=100)),
                ('order_Status', models.CharField(choices=[('ordered', 'ordered'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='ordered', max_length=20)),
                ('customername', models.CharField(max_length=200)),
                ('ordernumber', models.IntegerField(default=1)),
            ],
        ),
    ]
